import { useLanguage } from "../language";
import { useCoords } from "../store";
import { GearIcon } from "./icons";

/**
 * 「先连接模型」——凡是靠模型填满的地方，模型服务没配好时先说这一段（作者 2026-09-13：
 * 「这边的文字最应该首选是引导用户配置一个模型……在引导前边应该加个说明的语句」）。
 *
 * 一段话两句：**先说这一格为什么是空的**（它由模型生成），**再画那条路**——
 * ⚙ AI 设置 → 模型服务 → 服务地址 · 模型 · API 密钥 → 应用。每一站用的都是设置窗里
 * 那一栏 / 那一格真正的名字（`SettingsDrawer.tsx::TABS` 和三个 label），改了那边记得改这儿。
 * 「AI 设置」是一颗链接：点它直接开到「模型服务」那一栏（`openSettings("link")`），
 * 不让作者自己再找一次栏目。
 *
 * 四个消费方各说自己那句开场白：角色册 / 事件（从正文整理）、章节总结（生成）、
 * 写作助手（回话）。**只在 `model_configured` 为假时渲染**——判据在后端那一位，
 * 调用方读 `useAiSettings().data.model_configured`，这儿不再问一遍。
 */
export function ModelGuide({ what }: { what: "roster" | "events" | "summary" | "chat" }) {
  const language = useLanguage((s) => s.language);
  const openSettings = useCoords((s) => s.openSettings);
  const lead = LEAD[what][language];
  return (
    <div className="model-guide">
      <p className="model-guide-lead">{lead}</p>
      <p className="model-guide-steps">
        <button type="button" className="link model-guide-open" onClick={() => openSettings("link")}>
          <GearIcon />
          {language === "zh" ? "AI 设置" : "AI Settings"}
        </button>
        <span aria-hidden="true"> → </span>
        {language === "zh" ? "模型服务" : "Connection"}
        <span aria-hidden="true"> → </span>
        {language === "zh" ? "服务地址 · 模型 · API 密钥" : "Endpoint · Model · API key"}
        <span aria-hidden="true"> → </span>
        {language === "zh" ? "应用" : "Apply"}
      </p>
    </div>
  );
}

const LEAD = {
  roster: {
    zh: "角色册由模型从正文中整理，需先连接模型服务：",
    en: "The roster is compiled from the text by a model; connect a model service first:",
  },
  events: {
    zh: "事件由模型从正文中整理，需先连接模型服务：",
    en: "Events are compiled from the text by a model; connect a model service first:",
  },
  summary: {
    zh: "章节总结由模型生成，需先连接模型服务：",
    en: "Chapter summaries are generated by a model; connect a model service first:",
  },
  chat: {
    zh: "写作助手需先连接模型服务：",
    en: "The writing assistant needs a model service first:",
  },
} as const;
